# docker-compose.yml

version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    command: bash -c 'uvicorn api.main:app --host 0.0.0.0 --proxy-headers --port 8000'
    volumes:
      - .:/app
    ports:
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      # - "traefik.http.routers.api.entrypoints=web"
    networks:
      - "order-net"
  web:
    build:
      context: .
      dockerfile: Dockerfile-dashboard
    command: python dashboard/app.py
    volumes:
      - .:/app
    ports:
      - 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`web.localhost`)"
      # - "traefik.http.routers.dashboard.entrypoints=web"
    networks:
      - "order-net"
  reverse-proxy:
      image: traefik:latest
      ports:
        - "8080:8080"
        - "80:80"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      networks:
        - "order-net"

networks:
  order-net:
      
