version: '3.8'

services:
  # speech:
  #   build:
  #     context: .
  #     dockerfile: speech/Dockerfile
  #   command: python speech/process.py
  #   volumes:
  #     - .:/app
  #   networks:
  #     - "order-net"
  api-kk-cardiff:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: bash -c 'python -m uvicorn api.main:app --host 0.0.0.0 --proxy-headers --port 8001' 
    volumes:
      - .:/app
    ports:
      - 8001
    environment:
      BRAND_NAME: "kk"
      SHOP_NAME: "cardiff"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-kk-cardiff.rule=Host(`kk-cardiff.api.localhost`)"
      # - "traefik.http.routers.api.entrypoints=web"
    networks:
      - "order-net"
  web-kk-cardiff:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    command: python -m flask run -h 0.0.0.0 -p 5001
    volumes:
      - .:/app
    ports:
      - 5001
    environment:
      API_PORT: 8001
      BRAND_NAME: "kk"
      SHOP_NAME: "cardiff"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-kk-cardiff.rule=Host(`kk-cardiff.web.localhost`)"
      # - "traefik.http.routers.dashboard.entrypoints=web"
    networks:
      - "order-net"
  api-kk-leicester:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: bash -c 'python -m uvicorn api.main:app --host 0.0.0.0 --proxy-headers --port 8002' 
    volumes:
      - .:/app
    ports:
      - 8002
    environment:
      BRAND_NAME: "kk"
      SHOP_NAME: "leicester"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-kk-leicester.rule=Host(`kk-leicester.api.localhost`)"
      # - "traefik.http.routers.api.entrypoints=web"
    networks:
      - "order-net"
  web-kk-leicester:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    command: python -m flask run -h 0.0.0.0 -p 5002
    volumes:
      - .:/app
    ports:
      - 5002
    environment:
      API_PORT: 8002
      BRAND_NAME: "kk"
      SHOP_NAME: "leicester"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-kk-leicester.rule=Host(`kk-leicester.web.localhost`)"
      # - "traefik.http.routers.dashboard.entrypoints=web"
    networks:
      - "order-net"
  # api-pret:
  #   build:
  #     context: .
  #     dockerfile: api/Dockerfile
  #   command: bash -c 'python -m uvicorn api.main:app --host 0.0.0.0 --proxy-headers --port 8002' 
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 8002
  #   environment:
  #     SHOP_NAME: "pret"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.api-pret.rule=Host(`pret.api.localhost`)"
  #     # - "traefik.http.routers.api.entrypoints=web"
  #   networks:
  #     - "order-net"
  # web-pret:
  #   build:
  #     context: .
  #     dockerfile: dashboard/Dockerfile
  #   command: python -m flask run -h 0.0.0.0 -p 5002
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 5002
  #   environment:
  #     API_PORT: 8002
  #     SHOP_NAME: "pret"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.web-pret.rule=Host(`pret.web.localhost`)"
  #     # - "traefik.http.routers.dashboard.entrypoints=web"
  #   networks:
  #     - "order-net"
  # api-starbucks:
  #   build:
  #     context: .
  #     dockerfile: api/Dockerfile
  #   command: bash -c 'python -m uvicorn api.main:app --host 0.0.0.0 --proxy-headers --port 8003' 
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 8003
  #   environment:
  #     SHOP_NAME: "starbucks"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.api-starbucks.rule=Host(`starbucks.api.localhost`)"
  #     # - "traefik.http.routers.api.entrypoints=web"
  #   networks:
  #     - "order-net"
  # web-starbucks:
  #   build:
  #     context: .
  #     dockerfile: dashboard/Dockerfile
  #   command: python -m flask run -h 0.0.0.0 -p 5003
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 5003
  #   environment:
  #     API_PORT: 8003
  #     SHOP_NAME: "starbucks"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.web-starbucks.rule=Host(`starbucks.web.localhost`)"
  #     # - "traefik.http.routers.dashboard.entrypoints=web"
  #   networks:
  #     - "order-net"
  reverse-proxy:
      image: traefik:latest
      ports:
        - "8080:8080"
        - "80:80"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - "./traefik.dev.toml:/etc/traefik/traefik.toml"
        # - ".:/tmp/logs"
      networks:
        - "order-net"

networks:
  order-net:
      
